### ISSUE TITLE
Error installing crifx

### ISSUE THREAD

**Issue by SnowyOwl000** [FinnLidbetter/crifx#2]
When installing I get the following error:

> ERROR: Could not find a version that satisfies the requirement crifx (from versions: none)
> ERROR: No matching distribution found for crifx

**Comment by FinnLidbetter** [comment]
I think this error comes from using a python version less than 3.11. 

I worked through this with Bob Roos. We needed to create a python virtual environment.
If `python3 --version` gives 3.11 or 3.12, then I think the following should work:

```
# Create a directory to save virtual environments in.
cd ~
mkdir .venv
cd .venv
mkdir crifx   # Create a virtual environment directory for crifx and its dependencies
python3 -m venv ~/.venv/crifx
# Activate the virtual environment
source ~/.venv/crifx/bin/activate  # You can look at what this does with `cat ~/.venv/crifx/bin/activate`

# Then to install crifx you should be able to do:
python3 -m pip install crifx
# If you want to see what python packages have been installed, you can run:
python3 -m pip freeze
```
If you want to “deactivate” the virtual environment and go back to an environment where these packages are not installed, you can run
```
deactivate
```
`deactivate` is one of the commands defined by sourceing the ~/.venv/crifx/bin/activate file (edited) 


If you wanted other virtual environments that are independent from this one for crifx you could then, for example, create a new directory ~/.venv/something-else and run python3 -m venv ~/.venv/something-else and source ~/.venv/something-else/bin/activate

**Comment by SnowyOwl000** [comment]
My version is 3.8.10. Running your instructions yields the same result.

I will attempt to update the python system.

**Comment by FinnLidbetter** [comment]
Ok thanks for the update. I will see if I can reproduce the issue and get that fixed.
